source 'https://rubygems.org'

gem 'nokogiri',   '~> 1.6.3.1'
gem 'chef',       '~> 11.16.0'
gem 'berkshelf',  '~> 3.0.0'
gem 'chefspec',   '~> 4.2.0'
gem 'foodcritic', '~> 4.0.0'
gem 'rake'
gem 'test-kitchen'
gem 'kitchen-vagrant'
gem 'vagrant-wrapper'
